version: "3.7"
services:
  rtmp:
    build: .
    env_file: .env
    ports:
      - "1935:1935"
  rtmp-auth:
    image: node:12-alpine
    command: node /auth/index.js
    expose:
      - 19350
    env_file: .env
    volumes:
      - ./auth:/auth
