name: CI

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # captain/nginx-rtmp

      - name: Build and push captain/nginx-rtmp server
        id: nginx_rtmp_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-rtmp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: captain/nginx-rtmp configuration image digest
        run: echo ${{ steps.nginx_rtmp_build.outputs.digest }}

      # captain/nginx-rtmp-auth

      - name: Build and push captain/nginx-rtmp-auth server
        id: nginx_rtmp_auth_build
        uses: docker/build-push-action@v2
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-rtmp:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: captain/nginx-rtmp-auth server image digest
        run: echo ${{ steps.nginx_rtmp_auth_build.outputs.digest }}
